# conda env create -f environment.yml
# conda env remove -n ENV_NAME
name: wrfplot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - conda-forge::libpython-static
  - conda-forge::wrf-python=1.3.4
  - conda-forge::netcdf4
  - conda-forge::cartopy
  - conda-forge::imageio
  - conda-forge::nuitka=0.8.4
  - conda-forge::ordered-set
  - conda-forge::tqdm
  - conda-forge::wrapt
  - conda-forge::psutil
  # - conda-forge::patchelf
  - conda-forge::scons
  - conda-forge::pip
  - conda-forge::black  # use it only for code formatting. `black /path/to/python/package`
  - pip:
    - sphinx
    - sphinx_rtd_theme
    # - pyinstaller  # Not required as of now as nuitka works fine on Linux and Windows
    