site_name: wrfplot
site_url: https://wxguy.github.io/wrfplot

nav:
  - Home: index.md
  - Installation: install.md
  - Variables : variable-list.md
  - Usage: usage.md
  - Colormaps: colormaps.md
  - Support: support.md
  - Contribution: contribution.md
  - Authors: authors.md
  - License: license.md

theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
