[build-system]
#requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "wheel"]
requires = ["setuptools>=45", "versioneer[toml]", "wheel"]
build-backend = "setuptools.build_meta"

#[tool.setuptools_scm]
#write_to = "wrfplot/_version.py"
#version_scheme = "python-simplified-semver"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "wrfplot/_version.py"
versionfile_build = "wrfplot/_version.py"
tag_prefix = ""
parentdir_prefix = "wrfplot-"


[project]
dynamic = ["version",]
#version = "0.1.0"
authors = [{ name = "J Sundar", email = "wrf.guy@gmail.com" }]
name = "wrfplot"
description = "Command line application to plot WRF model output data"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["Scientific", "Engineering", "Atmospheric Science", "Weather Model", "Plotting", "Software Development", "Numerical Weather Prediction", "NWP"]
license = {text = "GPL3"}
classifiers = [
	"License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: Unix",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: Implementation :: CPython",
]

dependencies = ["cartopy", "xarray", "wrf-python>= 1.3", "netcdf4"]

[project.scripts]
wrfplot = "wrfplot.wrfplot:main"

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters

[tool.setuptools]
include-package-data = false
