name: "Build Windows setup for wrfplot"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-windows:
    name: Building Windows setup file
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Setting up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Install wrfplot conda environment
        run: |
          $CONDA\bin\conda env create -f environment.yml
      - name: Conda info
        run: |
          $CONDA\bin\conda info
          $CONDA\bin\conda info --envs
          $CONDA\bin\conda list
      - name: Running nuitka
        run: |
          $CONDA_PREFIX\envs\wrfplot\bin\python build_exe.py
      - name: Create installer
        uses: joncloud/makensis-action@v3.7
