name: "Build Windows setup for wrfplot"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-windows:
    name: Building Windows setup file
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Setting up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          auto-update-conda: true
      - name: Conda list
        shell: pwsh
        run: |
          conda list
          conda info
          conda info --envs
      - name: Install wrfplot conda environment
        shell: pwsh
        run: |
          conda env create -f environment.yml
          conda activate wrfplot
      - name: Running nuitka
        shell: pwsh
        run: |
          conda activate wrfplot
          python build_exe.py
      - name: Create installer
        uses: joncloud/makensis-action@v3.7
