name: "Build Windows setup for wrfplot"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-windows:
    name: Building Windows setup file
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      # Download NSIS plugin and extract it to NSIS directory
      - name: Download EnVar plugin for NSIS
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip
          file-name: envar_plugin.zip
          location: ${{ github.workspace }}
      - name: Extract EnVar plugin
        run: 7z x "${{ github.workspace }}/envar_plugin.zip" -o"C:\Program Files (x86)\NSIS"
      # Setup conda Python
      - name: Setting up conda base
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          auto-update-conda: true
      - name: Conda list env
        shell: pwsh
        run: |
          conda list
          conda info
          conda info --envs
      # Create wrfplot env and install necessary packages
      - name: Install wrfplot conda environment
        shell: pwsh
        run: |
          conda env create -f environment.yml
          conda activate wrfplot
      # Compile the wrfplot programe
      - name: Running nuitka
        shell: pwsh
        run: |
          conda activate wrfplot
          python build_exe.py
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: wrfplot-windows-64bit.exe
          path: build\windows\wrfplot-windows-64bit.exe
      #- name: Create installer
      #  uses: joncloud/makensis-action@v3.7
