name: "Build and release wrfplot Windows exectable"
# This workflow is triggered on push with tag to the repository.
on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setting up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          auto-update-conda: true
      - name: Downloading NSIS Plugin
        uses: carlosperate/download-file-action@v1.1.1
        with:
          file-url: https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip
          file-name: envar_plugin.zip
          location: ${{ github.workspace }}
      - name: Installing EnVar Plugin
        run: 7z x "${{ github.workspace }}/envar_plugin.zip" -o"C:\Program Files (x86)\NSIS"
      - name: Building Executable on Windows
        shell: pwsh
        run: |
          conda env create -f environment.yml
          conda activate wrfplot
          python build_exe.py
      - name: Release Process for Windows
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/windows/wrfplot-windows-64bit.exe
