name: "Build and release wrfplot Linux exectables"
# This workflow is triggered on push with tag to the repository.
on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setting up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          auto-update-conda: true
      - name: Build Binary on Linux
        shell: bash -l {0}
        run: |
          sudo apt-get update
          sudo apt-get install patchelf gdb ccache patchelf makeself libfuse2 build-essential gcc-7 -y
          conda env create -f environment.yml
          conda activate wrfplot
          export CC=gcc-7
          python build_exe.py
      - name: Release Process for Linux
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/linux/wrfplot-linux-64bit.run
